
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UnivarsityManagementSystem
{

using System;
    using System.Collections.Generic;
    
public partial class AdminInfo
{

    public int ID { get; set; }

    public string AdminName { get; set; }

    public string AdminPass { get; set; }

    public System.DateTime DOB { get; set; }

    public string Email { get; set; }

    public string UserType { get; set; }

}

}
