
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UnivarsityManagementSystem
{

using System;
    using System.Collections.Generic;
    
public partial class SectionStudent
{

    public int ID { get; set; }

    public int SecStudentName { get; set; }

    public int CouID { get; set; }

    public int MidTerm { get; set; }

    public int FinalTerm { get; set; }

    public int Total { get; set; }


        public string SSNM
        {
            get
            {
                if (this.StudentInfo == null)
                    return "-";

                return this.StudentInfo.StudentName;
            }
        }

        public string SSCourse
        {
            get
            {
                if (this.TeacherRegistration == null)
                    return "-";

                return this.TeacherRegistration.TRCourse;
            }
        }

        public virtual StudentInfo StudentInfo { get; set; }

    public virtual TeacherRegistration TeacherRegistration { get; set; }

}

}
