
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UnivarsityManagementSystem
{

using System;
    using System.Collections.Generic;
    
public partial class StudentRegistration
{

    public int ID { get; set; }

    public int SRCourse { get; set; }

    public int SRSec { get; set; }


        public string SRCourseNM
        {
            get
            {
                if (this.Course == null)
                    return "-";

                return this.Course.course_name;
            }
        }

        public string SRSecNM
        {
            get
            {
                if (this.Section == null)
                    return "-";

                return this.Section.SectionName;
            }
        }

        public virtual Course Course { get; set; }

    public virtual Section Section { get; set; }

}

}
