
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UnivarsityManagementSystem
{

using System;
    using System.Collections.Generic;
    
public partial class TeacherNoticeInfo
{

    public int ID { get; set; }

    public int TNCourse { get; set; }

    public string TNSec { get; set; }

    public string TNNotice { get; set; }

        public string TNCourseNM
        {
            get
            {
                if (this.TeacherRegistration == null)
                    return "-";

                return this.TeacherRegistration.TRCourse;
            }
        }


        public virtual TeacherRegistration TeacherRegistration { get; set; }

}

}
