
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UnivarsityManagementSystem
{

using System;
    using System.Collections.Generic;
    
public partial class TeacherRegistration
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TeacherRegistration()
    {

        this.SectionStudents = new HashSet<SectionStudent>();

        this.TeacherNoticeInfoes = new HashSet<TeacherNoticeInfo>();

    }


    public int ID { get; set; }

    public int TRCourseID { get; set; }

    public int TRSecID { get; set; }

        public string TRCourse
        {
            get
            {
                if (this.Course == null)
                    return "-";

                return this.Course.course_name;
            }
        }

        public string TRSec
        {
            get
            {
                if (this.Section == null)
                    return "-";

                return this.Section.SectionName;
            }
        }

        public virtual Course Course { get; set; }

    public virtual Section Section { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SectionStudent> SectionStudents { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TeacherNoticeInfo> TeacherNoticeInfoes { get; set; }

}

}
