

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UnivarsityManagementSystem
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class UMS_DatabaseEntities : DbContext
{
    public UMS_DatabaseEntities()
        : base("name=UMS_DatabaseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AdminInfo> AdminInfoes { get; set; }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Section> Sections { get; set; }

    public virtual DbSet<SectionStudent> SectionStudents { get; set; }

    public virtual DbSet<StudentInfo> StudentInfoes { get; set; }

    public virtual DbSet<StudentRegistration> StudentRegistrations { get; set; }

    public virtual DbSet<TeacherInfo> TeacherInfoes { get; set; }

    public virtual DbSet<TeacherNoticeInfo> TeacherNoticeInfoes { get; set; }

    public virtual DbSet<TeacherRegistration> TeacherRegistrations { get; set; }

}

}

